### ISSUE TITLE
seems not work on django 2.0?

### ISSUE THREAD

**Issue by nevermorever** [heywbj/django-rest-framework-recursive#26]

**Comment by nevermorever** [comment]
just a very simple model but seems dosent work
```python
class Catagory(models.Model):
    name = models.CharField(max_length=32)
    parent = models.ForeignKey('self', null=True, blank=True)


class CatagorySerializer(serializers.ModelSerializer):
    children = RecursiveField(allow_null=True, many=True)

    class Meta:
        model = Catagory
        fields = '__all__'


class CatagoryViewSet(viewsets.ModelViewSet):
    queryset = Catagory.objects.all()
    serializer_class = CatagorySerializer
```
and i got a output such as:
```python

[
    {
        "id": 5,
        "children": null,
        "name": "cata1",
        "parent": null
    },
    {
        "id": 6,
        "children": null,
        "name": "cata 1-1",
        "parent": 5
    }
]
```
this 'children' field of serializer output is always null, any thing wrong with my code ?

**Comment by heywbj** [comment]
Yes you are doing it wrong. The way you have defined it, "CatagorySerializer" looks for a field named "children" on the "Catagory" model. There is no such field, so it will always be null
